### ISSUE TITLE
psycopg2 needs to be bumped in requirements.txt

### ISSUE THREAD

**Issue by jensenja** [StackStorm-Exchange/stackstorm-sql#14]
current spec for psycopg2 in requirements.txt (`<=2.7.5`) is causing build/pack installation failures on Python 3.8 which is what comes with ST2 v3.5.0

i had to bump psycopg2 to `<=2.8` in requirements.txt for this pack to properly build and install.

**Comment by amanda11** [comment]
Thank you for raising the issue.
We accept PR submissions if you would like to submit a PR with an update the requirements file.

The old requirement probably was there when we had to support both python 2 and 3. But all the latest packs only list python3 so it should be ok to update the dependency as long as it can be met on python 3.6 and 3.8.

**Comment by jensenja** [comment]
reference #15

**Comment by armab** [comment]
Fixed via https://github.com/StackStorm-Exchange/stackstorm-sql/pull/15
