### ISSUE TITLE
Need a pack version bump, config.scheme from release != master

### ISSUE THREAD

**Issue by namachieli** [StackStorm-Exchange/stackstorm-sql#2]
The current tagged release's [config.scheme.yaml](https://github.com/StackStorm-Exchange/stackstorm-sql/blob/f4c7bb077bea221fd5c555fb05d3407397f60510/config.schema.yaml) is an empty yaml file, different from the [current master branch](https://github.com/StackStorm-Exchange/stackstorm-sql/blob/master/config.schema.yaml).

This is causing issues when installing the pack by version number and loading a config.

**Comment by blag** [comment]
Closed by #3.
