### ISSUE TITLE
stackstorm-sql Not returning results for MSSQL

### ISSUE THREAD

**Issue by anandjoshi77** [StackStorm-Exchange/stackstorm-sql#4]
Hello team, 
I have installed the stackstorm-sql pack and tried to execute commands. 
The commands executed for MySQL and Oracle return results, but when I execute queries for MSSQL, the query runs successfully but results are blank,
I get following output 

st2 run sql.query connection="mssql2" query="SELECT [Emp_ID],[Emp_Name],[Emp_Dept] FROM employee WHERE Emp_ID=1"

status: succeeded
parameters:
  connection: mssql2
  query: SELECT [Emp_ID],[Emp_Name],[Emp_Dept] FROM employee WHERE Emp_ID=1

result:
  exit_code: 0
  result: []
  stderr: ''
  stdout: ''
 
When I execute INSERT query, it returns 
result:
  exit_code: 0
  result:
    affected_rows: 1
  stderr: ''
  stdout: ''

The problem is with MSSQL SELECT query only.

**Comment by bishopbm1** [comment]
Hello @anandjoshi77,

I am testing trying to recreate this issue. Can you share your connection data? Specifically the username field?

Thank you,
Bradley Bishop

**Comment by anandjoshi77** [comment]
Hello @bishopbm1 

Not sure what you mean by connection data. 

I have created the config as suggested and it looks like below 


`---
connections:
  mssql:
    host: <my_sql_ip/instance_name>
    username: sa
    password: myPassw0rd
    database: employee
    drivername: mssql`

**Comment by anandjoshi77** [comment]
Just an update, 

I tried changing the python file.

Commented below code 

 `return_result = {'affected_rows': query_result.rowcount}`
`if query_result.returns_rows:`

after this, now I can see the results.

**Comment by nmaludy** [comment]
Fixes by #6
